# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('vip', models.IntegerField(db_column='VIP')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team1_name', models.CharField(max_length=20)),
                ('team2_name', models.CharField(max_length=20)),
                ('game_data_time', models.DateTimeField()),
                ('ticket_price', models.IntegerField()),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'stadiums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lab2_App.Customer')),
                ('sell_data_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'facts',
                'managed': False,
            },
        ),
    ]
